### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by annadiVreddy** [aadel112/googoose#4]
GET https://github.com/aadel112/googoose/jquery.googoose.js 404 (Not Found)

This is the error i get every time i run the application.

**Comment by feliciakrismanta** [comment]
Yes, accessing the link directly would only return a JSON file containing 
`{"error":"Not Found"}`

I included the raw file and it seems to be working
`<script type="text/javascript" src="https://raw.githubusercontent.com/aadel112/googoose/master/jquery.googoose.js"></script>`

I forked the project and created a release that can be accessed from a CDN
`<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/feliciakrismanta/googoose@v0.2-alpha/jquery.googoose.js"></script>`

**Comment by aadel112** [comment]
Thanks, I've made a similar update.

b9ff9b15ec13521b9f54ec73a7c6ae5c7cc08edb
