### ISSUE TITLE
Header and footer word question marks.

### ISSUE THREAD

**Issue by jondo89** [aadel112/googoose#8]
Hi there,

I am trying to implement the headers and footers, and have a constant error on the word doc with a question mark icon inside a square, this cannot be deleted in the word document. Applies to the header item as well.
`of 160 `
Tried the following at this point :
1. Change font - removes with some fonts, but cannot be deleted
2. Copied to note pad, this text box on Github,  - nothing
3. toggle field codes in Word - nothing.
4. open in word as .doc, then open in sublime and save - nothing
5. Make an unrelated change to text inside doc - nothing
6. in Sublime make format changes and resave as new filename - nothing

`<table id="googoose-hdrftrtbl">
            <tbody>
              <tr>
                <td class="h">
                </td>
                <td class="f">
                  <div style="mso-element:footer" id="googoose-footer">
                    <div class="googoose footer">
                      ofttt 
                      <span class="googoose totalpage">
                              
                            <span class="MsoPageNumber">
                              <span style="mso-no-proof:yes">
                                1
                              </span>
                              </span>
                            </span>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>`

7. Systematically remove items in the text above until the icon disappears - Works when the commented area below is blank. At this point, the icon disappears.

`<table id="googoose-hdrftrtbl">
            <tbody>
              <tr>
                <td class="h">
                </td>
                <td class="f">
                  <div style="mso-element:footer" id="googoose-footer">
                    if this is blank here , then there is no icon.
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
`
8. Messed around with the styles, and found that by moving code into normal body and not the header, that the symbol now displays as an  "	End Of Cell Marker (tables) "  when the paragraphs are shown.
9. Deleted table elements in the footer, new code from 6. now HTML code looks like this 

```
<div style="mso-element:footer" id="googoose-footer">
            <div class="googoose footer">
             of <span class="googoose totalpage">
         <!--[if supportFields]><span class=MsoPageNumber>
         <span style='mso-element:field-begin'>
         </span> NUMPAGES <span style='mso-element:field-separator'>
         </span>
       </span>
     <![endif]-->
     <span class="MsoPageNumber">
       <span style="mso-no-proof:yes">
        1
      </span>
    </span>
 <!--[if supportFields]>
 <span  class=MsoPageNumber>
 <span style='mso-element:field-end'>
 </span>
 </span>
<![endif]-->
</span>
</div>
</div>
```

This now works. Might be the table, might be the style on the table ... will update this post with details.

Update : 
By adding random text link this 👍 
`</tbody>asdasda</table>`
The icon disappears, however, the TBODY is auto-added to the HTML, and nearly impossible to modify using the jquery appends.

**Comment by jondo89** [comment]
```
if( fvis ) {
                var new_footer = thtml.find(options.footerarea)[0].outerHTML;
                thtml.find(options.footerarea).replaceWith('');
                thtml.find('table#' + options.headerfooterid + ' .f').append( 
                        GG.footerstart() + new_footer + GG.footerend());

                thtml.find('#'+options.headerfooterid+'').append('Adding random text here fixes this issue') 
                html = thtml[0].outerHTML;
            }
```

As shown above, fixes the problem, but really not sure what the root of this issue really is, it has something to do with the 

`var thtml = $(html);` 

which somehow modifies the HTML text using jquery, this then fails within word doc. 

Above my pay grade!

**Comment by jondo89** [comment]
```
 var thtml = $('<div>' + html + '</div>' );
                var hdrftr = $('<div id=\'' + options.headerfooterid + '\'></div>');
                hdrftr.append('<div><div class=headerArea></div><div class=footerArea></div></div>');
```

Rather than appending random text, changing the header and footers to divs rather than tables has worked fine.

**Comment by MohammedHyderAli** [comment]
> ```
>   GG.convert_hdrftr = function( html ) {
>             if( options.debug )
>                 GG.debug_fn('GG.convert_hdrftr');
>             var hvis = options.headerarea && $(options.headerarea).length;
>             var fvis = options.footerarea && $(options.footerarea).length;
>             if( hvis || fvis ) {
>                 var thtml = $('<div>' + html + '</div>' );
>                 var hdrftr = $('<div id=\'' + options.headerfooterid + '\'></div>');
>                 hdrftr.append('<div><div class=headerArea></div><div class=footerArea></div></div>');
>                 thtml.append(hdrftr);
>                 html = thtml[0].outerHTML;
> 
>                 html = GG.convert_totalpage(html);
>                 html = GG.convert_currentpage(html);
>             }
> 
>             var thtml = $(html);
>             if( hvis ) {
>                 var new_header = thtml.find(options.headerarea)[0].outerHTML;
>                 thtml.find(options.headerarea).replaceWith('');
>                 thtml.find('#' + options.headerfooterid + ' .h').append( 
>                         GG.headerstart() + new_header + GG.headerend() );
>                 html = thtml[0].outerHTML;
>             }
>             if( fvis ) {
>                 var new_footer = thtml.find(options.footerarea)[0].outerHTML;
>                 thtml.find(options.footerarea).replaceWith('');
>                 thtml.find('#' + options.headerfooterid + ' .f').append( 
>                         GG.footerstart() + new_footer + GG.footerend());
>                 html = thtml[0].outerHTML;
>             }
>             return html;
> 
>         }
> ```
> 
> Rather than appending random text, changing the header and footers to divs rather than tables has worked to fix the square question mark icon issue in ms word.

Yes @jondo89, it is working fine with your fix.
but one typo, we need to replace headerArea and footerArea class with h and f respectively to work perfectly

**Comment by aadel112** [comment]
Thanks for the discussion. I've been gone from this project for a long time, but I'm going to try to actually maintain it now. I've merged your changes. 

05c88247823eab35cec5871acd82480733f633d4
